Analysing EMG Signals from a dataset once completed we will do the following:
Make a packet structure in the data simulator for structured and more reliable data transfer
Apply these techniques to the continous stream

In [94]:
# import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from neurokit2.emg import emg_simulate

In [95]:
ax = np.load("/mnt/Sector16/nid24/nsys/recorder/0.npy")
print(ax)

[[ 0.007812  0.007812  0.007812 ... -0.023438 -0.023438 -0.023438]
 [-0.03125  -0.03125  -0.03125  ... -0.023438 -0.023438 -0.023438]
 [-0.007812 -0.007812 -0.007812 ...  0.054688  0.054688  0.054688]]


In [96]:
ax.shape

(3, 1001)

In [109]:
generated = np.load("/mnt/Sector16/nid24/nsys/test_data/data.npy")
print(generated)

[[0.09087545 0.11679071 0.10062988 ... 0.12249475 0.08080196 0.07615569]
 [0.09149132 0.07616499 0.12060683 ... 0.10775576 0.02801618 0.10049341]
 [0.11422052 0.15323851 0.06790495 ... 0.08660205 0.07128939 0.08972235]]


In [110]:
generated.shape

(3, 60000)

In [103]:
ax[2]

array([-0.007812, -0.007812, -0.007812, ...,  0.054688,  0.054688,
        0.054688], shape=(1001,))